project:
  type: website
  output-dir: docs

website:
  title: "PHYS 216 Winter 2026"
  navbar:
    background: primary #color of background is primary color in palette
    search: true
    #left is left-aligned top bar
    left:
      - href: index.qmd
        text: Home
      - href: https://phys216.github.io/
        text: "Course Description"
        target: _blank #makes it open in new page
      - href: https://docs.google.com/spreadsheets/d/1RjA9_LdSXy4BB5bSa1Y8FqFShpdxaWhbSPhmuD1-9xo/edit?usp=sharing
        text: "Schedule" 
        target: _blank #makes it open in new page
      - sidebar:syllabus
      - sidebar:resources
            
  sidebar:
    - id: syllabus
      title: "Syllabus and FAQ"
      style: "docked"
      background: light
      contents:
       - starthere.qmd
       - syllabus.qmd
       - FAQ.qmd
       
    - id: resources
      title: "Resources"
      style: "docked"
      background: light
      contents:
       - resources.qmd

   
format:
  html:
    theme: bates_yeti.scss
    toc: true

